In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Project paths
PROJECT_DIR = Path(
    r"C:\India_Vs_West_Indies_T20i_Challenge"
)

RAW_DIR = PROJECT_DIR / "Data" / "Raw"
CLEAN_DIR = PROJECT_DIR / "Data" / "Clean"

CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# Locate the CSV file
csv_files = list(RAW_DIR.glob("*.csv"))

if not csv_files:
    raise FileNotFoundError(
        f"No CSV file found in {RAW_DIR}"
    )

# Load the raw data
df = pd.read_csv(csv_files[0])

print("Dataset loaded successfully")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

df.head()

Dataset loaded successfully
Shape: (959, 21)
Columns: ['Venue', 'MatchDay', 'Innings', 'Batting Team', 'Bowling Team', 'Striker', 'Non-Striker', 'Bowler', 'Ball Number', 'Actual Ball Number', 'Overs', 'Team Runs', 'Runs Off The Bat', 'Extra', 'Wide', 'No Ball', 'Leg Bye', 'Bye', 'Wicket', "4's", "6's"]

,Venue,MatchDay,Innings,Batting Team,Bowling Team,Striker,Non-Striker,Bowler,Ball Number,Actual Ball Number,...,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Wicket,4's,6's
0,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.1,0.1,...,0,0,0,0,0,0,0,0,0,0
1,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.2,0.2,...,0,0,0,0,0,0,0,0,0,0
2,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.3,0.3,...,0,0,0,0,0,0,0,0,0,0
3,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.4,0.4,...,4,4,0,0,0,0,0,0,1,0
4,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.5,0.5,...,0,0,0,0,0,0,0,0,0,0

In [2]:
# 1. Check dataset dimensions
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# 2. Check column names and data types
df.info()

# 3. Display all column names
for col in df.columns:
    print(col)

# 4. Check first and last 5 records
display(df.head())
display(df.tail())

Rows: 959
Columns: 21
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 959 entries, 0 to 958
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Venue               959 non-null    object
 1   MatchDay            959 non-null    int64
 2   Innings             959 non-null    int64
 3   Batting Team        959 non-null    object
 4   Bowling Team        959 non-null    object
 5   Striker             959 non-null    object
 6   Non-Striker         959 non-null    object
 7   Bowler              959 non-null    object
 8   Ball Number         959 non-null    float64
 9   Actual Ball Number  959 non-null    float64
 10  Overs               959 non-null    int64
 11  Team Runs           959 non-null    int64
 12  Runs Off The Bat    959 non-null    int64
 13  Extra               959 non-null    int64
 14  Wide                959 non-null    int64
 15  No Ball             959 non-null    int64
 16  Leg Bye             959 non-null    int64
 17  Bye                 959 non-null    int64
 18  Wicket              959 non-null    int64
 19  4's                 959 non-null    int64
 20  6's                 959 non-null    int64
dtypes: float64(2), int64(13), object(6)
memory usage: 157.5+ KB
Venue
MatchDay
Innings
Batting Team
Bowling Team
Striker
Non-Striker
Bowler
Ball Number
Actual Ball Number
Overs
Team Runs
Runs Off The Bat
Extra
Wide
No Ball
Leg Bye
Bye
Wicket
4's
6's

,Venue,MatchDay,Innings,Batting Team,Bowling Team,Striker,Non-Striker,Bowler,Ball Number,Actual Ball Number,...,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Wicket,4's,6's
0,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.1,0.1,...,0,0,0,0,0,0,0,0,0,0
1,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.2,0.2,...,0,0,0,0,0,0,0,0,0,0
2,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.3,0.3,...,0,0,0,0,0,0,0,0,0,0
3,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.4,0.4,...,4,4,0,0,0,0,0,0,1,0
4,Ekana Cricket Stadium B Ground,1,1,West Indies Cricket Team,India National Cricket team,Shai Hope,Kamil Pooran,Arshdeep Singh,0.5,0.5,...,0,0,0,0,0,0,0,0,0,0

,Venue,MatchDay,Innings,Batting Team,Bowling Team,Striker,Non-Striker,Bowler,Ball Number,Actual Ball Number,...,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Wicket,4's,6's
954,Rajiv Gandhi International Stadium,4,2,India National Cricket team,West Indies Cricket Team,Arshdeep Singh,Mayank Yadav,Shamar Joseph,19.1,19.1,...,4,4,0,0,0,0,0,0,1,0
955,Rajiv Gandhi International Stadium,4,2,India National Cricket team,West Indies Cricket Team,Arshdeep Singh,Mayank Yadav,Shamar Joseph,19.2,19.1,...,1,0,1,1,0,0,0,0,0,0
956,Rajiv Gandhi International Stadium,4,2,India National Cricket team,West Indies Cricket Team,Arshdeep Singh,Mayank Yadav,Shamar Joseph,19.3,19.2,...,0,0,0,0,0,0,0,0,0,0
957,Rajiv Gandhi International Stadium,4,2,India National Cricket team,West Indies Cricket Team,Arshdeep Singh,Mayank Yadav,Shamar Joseph,19.4,19.3,...,0,0,0,0,0,0,0,0,0,0
958,Rajiv Gandhi International Stadium,4,2,India National Cricket team,West Indies Cricket Team,Arshdeep Singh,Mayank Yadav,Shamar Joseph,19.5,19.3,...,5,0,5,5,0,0,0,0,0,0

In [3]:
# Missing values in each column
missing_values = df.isnull().sum()

missing_report = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percentage": (
        missing_values / len(df) * 100
    ).round(2)
})

display(
    missing_report[
        missing_report["Missing_Count"] > 0
    ].sort_values(
        "Missing_Count",
        ascending=False
    )
)

# Exact duplicate rows
print("Exact duplicate rows:", df.duplicated().sum())

# Check completely empty rows
print("Completely empty rows:", df.isna().all(axis=1).sum())

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

Exact duplicate rows: 0
Completely empty rows: 0

In [4]:
# Check numeric columns
display(df.describe(include="all").T)

# Check repeated player-name spellings
player_columns = [
    col for col in ["Batter", "Non-striker", "Bowler"]
    if col in df.columns
]

for col in player_columns:
    print(f"\nTop names in {col}:")
    display(df[col].value_counts(dropna=False).head(15))

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Venue,959,4,Rajiv Gandhi International Stadium,260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MatchDay,959.0,NaN,NaN,NaN,2.590198,1.101312,1.0,2.0,3.0,4.0,4.0
Innings,959.0,NaN,NaN,NaN,1.480709,0.499888,1.0,1.0,1.0,2.0,2.0
Batting Team,959,2,West Indies Cricket Team,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bowling Team,959,2,India National Cricket team,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Striker,959,28,Shai Hope,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Non-Striker,959,26,Shai Hope,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bowler,959,17,Arshdeep Singh,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ball Number,959.0,NaN,NaN,NaN,9.471534,5.584361,0.1,4.55,9.4,14.2,19.6
Actual Ball Number,959.0,NaN,NaN,NaN,9.449948,5.582256,0.1,4.5,9.4,14.2,19.6
Overs,959.0,NaN,NaN,NaN,10.105318,5.582403,1.0,5.0,10.0,15.0,20.0
Team Runs,959.0,NaN,NaN,NaN,1.819604,1.930362,0.0,0.0,1.0,4.0,6.0
Runs Off The Bat,959.0,NaN,NaN,NaN,1.733055,1.958777,0.0,0.0,1.0,4.0,6.0
Extra,959.0,NaN,NaN,NaN,0.084463,0.398534,0.0,0.0,0.0,0.0,5.0
Wide,959.0,NaN,NaN,NaN,0.051095,0.30048,0.0,0.0,0.0,0.0,5.0
No Ball,959.0,NaN,NaN,NaN,0.007299,0.085168,0.0,0.0,0.0,0.0,1.0
Leg Bye,959.0,NaN,NaN,NaN,0.016684,0.208717,0.0,0.0,0.0,0.0,4.0
Bye,959.0,NaN,NaN,NaN,0.012513,0.193447,0.0,0.0,0.0,0.0,4.0
Wicket,959.0,NaN,NaN,NaN,0.052138,0.222421,0.0,0.0,0.0,0.0,1.0
4's,959.0,NaN,NaN,NaN,0.156413,0.363436,0.0,0.0,0.0,0.0,1.0
6's,959.0,NaN,NaN,NaN,0.10219,0.303056,0.0,0.0,0.0,0.0,1.0

Top names in Bowler:

Bowler
Arshdeep Singh      105
Roston Chase         96
Mayank Yadav         95
Shamar Springer      83
Axar Patel           82
Shamar Joseph        74
Naman Dhir           63
Romario Shepherd     57
Keemo Paul           54
Prince Yadav         51
Kuldeep Yadav        49
Gudakesh Motie       49
Akeal Hosein         44
Nitish Reddy         30
Shivam Dube          13
Name: count, dtype: int64

In [6]:
# Create a copy for auditing; keep the original df unchanged
audit_df = df.copy()

# Calculate expected runs from batter runs + extras
audit_df["Run Difference"] = (
    audit_df["Team Runs"]
    - audit_df["Runs Off The Bat"]
    - audit_df["Extra"]
)

# Compare Extra against the sum of recorded extras components
extra_columns = ["Wide", "No Ball", "Leg Bye", "Bye"]

audit_df["Extra Component Difference"] = (
    audit_df["Extra"]
    - audit_df[extra_columns].sum(axis=1)
)

# Expected four and six indicators based on runs off the bat
audit_df["Expected 4's"] = (
    audit_df["Runs Off The Bat"] == 4
).astype(int)

audit_df["Expected 6's"] = (
    audit_df["Runs Off The Bat"] == 6
).astype(int)

# Summary of flagged records
print("Team-run mismatches:",
      (audit_df["Run Difference"] != 0).sum())

print("Extras-component mismatches:",
      (audit_df["Extra Component Difference"] != 0).sum())

print("Incorrect four indicators:",
      (audit_df["4's"] != audit_df["Expected 4's"]).sum())

print("Incorrect six indicators:",
      (audit_df["6's"] != audit_df["Expected 6's"]).sum())

Team-run mismatches: 2
Extras-component mismatches: 1
Incorrect four indicators: 2
Incorrect six indicators: 0

In [7]:
# Display complete records for each issue
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

print("TEAM RUN MISMATCHES")
display(
    audit_df.loc[
        audit_df["Run Difference"] != 0,
        df.columns
    ]
)

print("EXTRAS COMPONENT MISMATCH")
display(
    audit_df.loc[
        audit_df["Extra Component Difference"] != 0,
        df.columns
    ]
)

print("INCORRECT FOUR INDICATORS")
display(
    audit_df.loc[
        audit_df["4's"] !=
        (audit_df["Runs Off The Bat"] == 4).astype(int),
        df.columns
    ]
)

# Check innings and team consistency
print("MATCH DAY AND INNINGS DISTRIBUTION")
display(
    df.groupby(
        ["MatchDay", "Innings", "Batting Team", "Bowling Team"],
        dropna=False
    ).agg(
        Deliveries=("Ball Number", "size"),
        Total_Runs=("Team Runs", "sum"),
        Batting_Runs=("Runs Off The Bat", "sum"),
        Extras=("Extra", "sum"),
        Wickets=("Wicket", "sum")
    ).reset_index()
)

# Check player-name spelling variants
for col in ["Striker", "Non-Striker", "Bowler"]:
    print(f"\nUnique names in {col}:")
    print(sorted(df[col].dropna().unique()))

TEAM RUN MISMATCHES

,Venue,MatchDay,Innings,Batting Team,Bowling Team,Striker,Non-Striker,Bowler,Ball Number,Actual Ball Number,Overs,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Wicket,4's,6's
219,JSCA International Stadium Complex,2,1,India National Cricket team,West Indies Cricket Team,Sanju Samson,Abhishek Sharma,Akeal Hosein,2.3,2.2,3,0,0,1,0,1,0,0,0,0,0
458,Holkar Stadium,3,1,India National Cricket team,West Indies Cricket Team,Ishan Kishan,Abhishek Sharma,Shamar Joseph,1.5,1.5,2,4,0,1,0,0,0,4,0,0,0

EXTRAS COMPONENT MISMATCH

,Venue,MatchDay,Innings,Batting Team,Bowling Team,Striker,Non-Striker,Bowler,Ball Number,Actual Ball Number,Overs,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Wicket,4's,6's
458,Holkar Stadium,3,1,India National Cricket team,West Indies Cricket Team,Ishan Kishan,Abhishek Sharma,Shamar Joseph,1.5,1.5,2,4,0,1,0,0,0,4,0,0,0

INCORRECT FOUR INDICATORS

,Venue,MatchDay,Innings,Batting Team,Bowling Team,Striker,Non-Striker,Bowler,Ball Number,Actual Ball Number,Overs,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Wicket,4's,6's
604,Holkar Stadium,3,2,West Indies Cricket Team,India National Cricket team,Kamil Pooran,Shimron Hetmyer,Mayank Yadav,5.1,5.1,6,4,4,0,0,0,0,0,0,0,0
607,Holkar Stadium,3,2,West Indies Cricket Team,India National Cricket team,Shimron Hetmyer,Kamil Pooran,Mayank Yadav,5.4,5.4,6,4,4,0,0,0,0,0,0,0,0

MATCH DAY AND INNINGS DISTRIBUTION

   MatchDay  Innings                 Batting Team                 Bowling Team  Deliveries  Total_Runs  Batting_Runs  Extras  Wickets
0         1        1     West Indies Cricket Team  India National Cricket team         116         171           163       8       10
1         1        2  India National Cricket team     West Indies Cricket Team          89         172           171       1        2
2         2        1  India National Cricket team     West Indies Cricket Team         128         248           240       9        5
3         2        2     West Indies Cricket Team  India National Cricket team         115         252           248       4        4
4         3        1  India National Cricket team     West Indies Cricket Team         124         223           213       7       10
5         3        2     West Indies Cricket Team  India National Cricket team         127         209           199      10        7
6         4        1     West Indies Cricket Team  India National Cricket team         130         247           229      18        3
7         4        2  India National Cricket team     West Indies Cricket Team         130         223           199      24        9

Unique names in Striker:
['Abhishek Sharma', 'Akeal Hosein', 'Arshdeep Singh', 'Axar Patel', 'Ishan Kishan', 'Jewel Andrew', 'Kamil Pooran', 'Keemo Paul', 'Matthew Forde', 'Mayank Yadav', 'NItish Reddy', 'Naman Dhir', 'Nitish Reddy', 'Prince  Yaddav', 'Prince Yadav', 'Quentin Sampson', 'Romario Shepherd', 'Roston Chase', 'Rovman Powell', 'Sanju Samson', 'Shai Hope', 'Shamar Joseph', 'Shamar Springer', 'Sherfane Rutherford', 'Shimron Hetmyer', 'Shivam Dube', 'Shreyas Iyer', 'Tilak Varma']

Unique names in Non-Striker:
['Abhishek Sharma', 'Akeal Hosein', 'Arshdeep Singh', 'Axar Patel', 'Ishan Kishan', 'Jewel Andrew', 'Kamil Pooran', 'Keemo Paul', 'Matthew Forde', 'Mayank Yadav', 'Naman Dhir', 'Nitish Reddy', 'Prince Yadav', 'Quentin Sampson', 'Romario Shepherd', 'Roston Chase', 'Rovman Powell', 'Sanju Samson', 'Shai Hope', 'Shamar Joseph', 'Shamar Springer', 'Sherfane Rutherford', 'Shimron Hetmyer', 'Shivam Dube', 'Shreyas Iyer', 'Tilak Varma']

Unique names in Bowler:
['Akeal Hosein', 'Arshdeep Singh', 'Axar Patel', 'Gudakesh Motie', 'Keemo Paul', 'Kuldeep Yadav', 'Matthew Forde', 'Mayank Yadav', 'Naman Dhir', 'Nitish Reddy', 'Prince Yadav', 'Romario Shepherd', 'Roston Chase', 'Rovman Powell', 'Shamar Joseph', 'Shamar Springer', 'Shivam Dube']

In [8]:
# Create a clean copy; do not modify the original df
clean_df = df.copy()

# 1. Standardize whitespace and obvious name variants
name_columns = ["Striker", "Non-Striker", "Bowler"]

for col in name_columns:
    clean_df[col] = (
        clean_df[col]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

name_mapping = {
    "NItish Reddy": "Nitish Reddy",
    "Prince Yaddav": "Prince Yadav"
}

for col in name_columns:
    clean_df[col] = clean_df[col].replace(name_mapping)

# 2. Recalculate boundary indicators from batter runs
clean_df["4's"] = (
    clean_df["Runs Off The Bat"] == 4
).astype(int)

clean_df["6's"] = (
    clean_df["Runs Off The Bat"] == 6
).astype(int)

# 3. Preserve unresolved run/extras issues for investigation
clean_df["Run_QC_Flag"] = (
    clean_df["Team Runs"]
    != clean_df["Runs Off The Bat"] + clean_df["Extra"]
)

clean_df["Extras_QC_Flag"] = (
    clean_df["Extra"]
    != clean_df[["Wide", "No Ball", "Leg Bye", "Bye"]].sum(axis=1)
)

# 4. Save the cleaned dataset
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

clean_path = CLEAN_DIR / "t20i_ball_by_ball_clean.csv"
clean_df.to_csv(clean_path, index=False)

print("Clean dataset saved:", clean_path)
print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))
print("Run issues retained:", clean_df["Run_QC_Flag"].sum())
print("Extras issues retained:", clean_df["Extras_QC_Flag"].sum())
print("Four indicators now inconsistent:",
      (clean_df["4's"] !=
       (clean_df["Runs Off The Bat"] == 4).astype(int)).sum())
print("Six indicators now inconsistent:",
      (clean_df["6's"] !=
       (clean_df["Runs Off The Bat"] == 6).astype(int)).sum())

Clean dataset saved: C:\India_Vs_West_Indies_T20i_Challenge\Data\Clean\t20i_ball_by_ball_clean.csv
Rows: 959
Columns: 23
Run issues retained: 2
Extras issues retained: 1
Four indicators now inconsistent: 0
Six indicators now inconsistent: 0

In [9]:
match_summary = (
    clean_df.groupby(
        ["MatchDay", "Innings", "Batting Team", "Bowling Team"],
        as_index=False
    )
    .agg(
        Deliveries=("Ball Number", "size"),
        Total_Runs=("Team Runs", "sum"),
        Batter_Runs=("Runs Off The Bat", "sum"),
        Extras=("Extra", "sum"),
        Wickets=("Wicket", "sum"),
        Fours=("4's", "sum"),
        Sixes=("6's", "sum")
    )
)

display(match_summary)

# Check which matches have both innings recorded
print("\nInnings count per match:")
display(
    clean_df.groupby("MatchDay")["Innings"].nunique()
)

# Verify each innings has the expected batting/bowling team pairing
team_check = clean_df[
    ["MatchDay", "Innings", "Batting Team", "Bowling Team"]
].drop_duplicates()

display(
    team_check.sort_values(["MatchDay", "Innings"])
)

   MatchDay  Innings                 Batting Team                 Bowling Team  Deliveries  Total_Runs  Batter_Runs  Extras  Wickets  Fours  Sixes
0         1        1     West Indies Cricket Team  India National Cricket team         116         171          163       8       10     17      8
1         1        2  India National Cricket team     West Indies Cricket Team          89         172          171       1        2     19      7
2         2        1  India National Cricket team     West Indies Cricket Team         128         248          240       9        5     25     13
3         2        2     West Indies Cricket Team  India National Cricket team         115         252          248       4        4     21     20
4         3        1  India National Cricket team     West Indies Cricket Team         124         223          213       7       10     24      8
5         3        2     West Indies Cricket Team  India National Cricket team         127         209          199      10        7     15     13
6         4        1     West Indies Cricket Team  India National Cricket team         130         247          229      18        3     16     16
7         4        2  India National Cricket team     West Indies Cricket Team         130         223          199      24        9     15     13

Innings count per match:

MatchDay
1    2
2    2
3    2
4    2
Name: Innings, dtype: int64

     MatchDay  Innings                 Batting Team                 Bowling Team
0           1        1     West Indies Cricket Team  India National Cricket team
116         1        2  India National Cricket team     West Indies Cricket Team
205         2        1  India National Cricket team     West Indies Cricket Team
333         2        2     West Indies Cricket Team  India National Cricket team
448         3        1  India National Cricket team     West Indies Cricket Team
572         3        2     West Indies Cricket Team  India National Cricket team
699         4        1     West Indies Cricket Team  India National Cricket team
829         4        2  India National Cricket team     West Indies Cricket Team

In [10]:
# Rebuild the summary with explicit column names
innings_summary = (
    clean_df.groupby(
        ["MatchDay", "Innings", "Batting Team", "Bowling Team"],
        as_index=False
    )
    .agg(
        Deliveries=("Ball Number", "size"),
        Team_Runs=("Team Runs", "sum"),
        Batter_Runs=("Runs Off The Bat", "sum"),
        Extras=("Extra", "sum"),
        Wicket_Flags=("Wicket", "sum"),
        Fours=("4's", "sum"),
        Sixes=("6's", "sum")
    )
)

innings_summary["Runs_Reconciled"] = (
    innings_summary["Team_Runs"]
    == innings_summary["Batter_Runs"] + innings_summary["Extras"]
)

display(innings_summary.to_string(index=False))

# Inspect wicket values
print("\nWicket column values:")
print(clean_df["Wicket"].value_counts(dropna=False).sort_index())

# Show all rows marked as wickets
print("\nRows marked as wickets:")
display(
    clean_df.loc[
        clean_df["Wicket"] != 0,
        ["MatchDay", "Innings", "Striker", "Bowler",
         "Ball Number", "Team Runs", "Runs Off The Bat",
         "Extra", "Wicket"]
    ]
)

' MatchDay  Innings                Batting Team                Bowling Team  Deliveries  Team_Runs  Batter_Runs  Extras  Wicket_Flags  Fours  Sixes  Runs_Reconciled\n        1        1    West Indies Cricket Team India National Cricket team         116        171          163       8            10     17      8             True\n        1        2 India National Cricket team    West Indies Cricket Team          89        172          171       1             2     19      7             True\n        2        1 India National Cricket team    West Indies Cricket Team         128        248          240       9             5     25     13            False\n        2        2    West Indies Cricket Team India National Cricket team         115        252          248       4             4     21     20             True\n        3        1 India National Cricket team    West Indies Cricket Team         124        223          213       7            10     24      8            False\n        3        2    West Indies Cricket Team India National Cricket team         127        209          199      10             7     15     13             True\n        4        1    West Indies Cricket Team India National Cricket team         130        247          229      18             3     16     16             True\n        4        2 India National Cricket team    West Indies Cricket Team         130        223          199      24             9     15     13             True'

Wicket column values:
Wicket
0    909
1     50
Name: count, dtype: int64

Rows marked as wickets:

     MatchDay  Innings              Striker            Bowler  Ball Number  Team Runs  Runs Off The Bat  Extra  Wicket
27          1        1         Kamil Pooran    Arshdeep Singh          4.3          0                 0      0       1
32          1        1            Shai Hope        Axar Patel          5.2          0                 0      0       1
35          1        1        Rovman Powell        Axar Patel          5.5          0                 0      0       1
70          1        1            Shai Hope        Naman Dhir         11.4          0                 0      0       1
75          1        1         Roston Chase     Kuldeep Yadav         12.3          0                 0      0       1
80          1        1     Romario Shepherd        Naman Dhir         13.2          0                 0      0       1
85          1        1        Matthew Forde     Kuldeep Yadav         14.1          0                 0      0       1
95          1        1      Shamar Springer        Naman Dhir         15.5          0                 0      0       1
113         1        1  Sherfane Rutherford      Mayank Yadav         18.5          0                 0      0       1
115         1        1         Akeal Hosein      Mayank Yadav         19.1          0                 0      0       1
130         1        2      Abhishek Sharma      Roston Chase          2.3          0                 0      0       1
136         1        2         Sanju Samson      Akeal Hosein          3.3          0                 0      0       1
229         2        1      Abhishek Sharma      Roston Chase          3.6          0                 0      0       1
273         2        1         Ishan Kishan      Roston Chase         11.1          0                 0      0       1
292         2        1          Shivam Dube      Roston Chase         13.3          0                 0      0       1
298         2        1         Sanju Samson   Shamar Springer         14.3          0                 0      0       1
331         2        1         Shreyas Iyer   Shamar Springer         19.5          0                 0      0       1
335         2        2         Kamil Pooran      Mayank Yadav          0.3          0                 0      0       1
336         2        2      Shimron Hetmyer      Mayank Yadav          0.4          0                 0      0       1
363         2        2        Rovman Powell      Mayank Yadav          5.1          0                 0      0       1
420         2        2  Sherfane Rutherford     Kuldeep Yadav         14.1          0                 0      0       1
457         3        1         Sanju Samson     Shamar Joseph          1.4          0                 0      0       1
500         3        1         Ishan Kishan      Roston Chase          8.2          0                 0      0       1
503         3        1         Shreyas Iyer      Roston Chase          8.5          0                 0      0       1
510         3        1      Abhishek Sharma   Shamar Springer          9.6          0                 0      0       1
516         3        1           Naman Dhir    Gudakesh Motie         10.5          0                 0      0       1
537         3        1         Nitish Reddy        Keemo Paul         14.2          0                 0      0       1
551         3        1           Axar Patel    Gudakesh Motie         16.4          1                 1      0       1
560         3        1           Axar Patel   Shamar Springer         18.1          0                 0      0       1
565         3        1       Arshdeep Singh   Shamar Springer         18.6          0                 0      0       1
571         3        1         Mayank Yadav     Shamar Joseph         19.6          0                 0      0       1
582         3        2            Shai Hope    Arshdeep Singh          1.5          0                 0      0       1
616         3        2      Shimron Hetmyer        Naman Dhir          6.7          0                 0      0       1
632         3        2        Rovman Powell        Axar Patel          9.4          0                 0      0       1
641         3        2         Kamil Pooran        Naman Dhir         10.7          0                 0      0       1
671         3        2      Quentin Sampson      Nitish Reddy         15.3          0                 0      0       1
682         3        2           Keemo Paul    Arshdeep Singh         17.2          0                 0      0       1
685         3        2  Sherfane Rutherford    Arshdeep Singh         17.5          0                 0      0       1
727         4        1         Jewel Andrew        Axar Patel          4.2          0                 0      0       1
753         4        1      Shimron Hetmyer      Prince Yadav          8.2          0                 0      0       1
782         4        1        Rovman Powell    Arshdeep Singh         12.6          0                 0      0       1
855         4        2         Sanju Samson        Keemo Paul          4.1          0                 0      0       1
859         4        2         Ishan Kishan        Keemo Paul          4.5          0                 0      0       1
881         4        2         Shreyas Iyer   Shamar Springer          8.2          0                 0      0       1
901         4        2      Abhishek Sharma    Gudakesh Motie         11.3          0                 0      0       1
902         4        2           Naman Dhir    Gudakesh Motie         11.4          0                 0      0       1
940         4        2          Tilak Varma  Romario Shepherd         16.7          0                 0      0       1
949         4        2         Nitish Reddy        Keemo Paul         18.3          0                 0      0       1
950         4        2         Prince Yadav        Keemo Paul         18.4          0                 0      0       1
952         4        2           Axar Patel        Keemo Paul         18.6          0                 0      0       1

In [11]:
# Investigate MatchDay 2, Innings 1
# and MatchDay 3, Innings 1

problem_innings = [(2, 1), (3, 1)]

for match_day, innings_no in problem_innings:
    print(f"\nMatchDay {match_day} | Innings {innings_no}")

    subset = clean_df[
        (clean_df["MatchDay"] == match_day)
        & (clean_df["Innings"] == innings_no)
    ].copy()

    subset["Calculated_Runs"] = (
        subset["Runs Off The Bat"] + subset["Extra"]
    )

    subset["Run_Difference"] = (
        subset["Team Runs"] - subset["Calculated_Runs"]
    )

    display(
        subset.loc[
            subset["Run_Difference"] != 0,
            [
                "Venue", "Striker", "Bowler",
                "Ball Number", "Actual Ball Number",
                "Team Runs", "Runs Off The Bat", "Extra",
                "Wide", "No Ball", "Leg Bye", "Bye",
                "Wicket", "Run_Difference"
            ]
        ]
    )

# Check invalid ball suffixes in the displayed ball number
ball_suffix = (
    clean_df["Ball Number"].mod(1).mul(10).round().astype(int)
)

print("\nBall-number suffix counts:")
display(ball_suffix.value_counts().sort_index())

MatchDay 2 | Innings 1

                                  Venue       Striker        Bowler  Ball Number  Actual Ball Number  Team Runs  Runs Off The Bat  Extra  Wide  No Ball  Leg Bye  Bye  Wicket  Run_Difference
219  JSCA International Stadium Complex  Sanju Samson  Akeal Hosein          2.3                 2.2          0                 0      1     0        1        0    0       0              -1

MatchDay 3 | Innings 1

              Venue       Striker         Bowler  Ball Number  Actual Ball Number  Team Runs  Runs Off The Bat  Extra  Wide  No Ball  Leg Bye  Bye  Wicket  Run_Difference
458  Holkar Stadium  Ishan Kishan  Shamar Joseph          1.5                 1.5          4                 0      1     0        0        0    4       0               3

Ball-number suffix counts:

Ball Number
1    155
2    153
3    153
4    152
5    151
6    150
7     35
8      6
9      4
Name: count, dtype: int64

In [12]:
# Inspect deliveries whose Ball Number suffix is greater than 6

ball_suffix = (
    clean_df["Ball Number"]
    .mod(1)
    .mul(10)
    .round()
    .astype(int)
)

unusual_balls = clean_df.loc[
    ball_suffix > 6,
    [
        "MatchDay",
        "Innings",
        "Batting Team",
        "Bowling Team",
        "Striker",
        "Bowler",
        "Ball Number",
        "Actual Ball Number",
        "Team Runs",
        "Runs Off The Bat",
        "Extra",
        "Wide",
        "No Ball",
        "Leg Bye",
        "Bye",
    ],
].copy()

print("Deliveries with suffix greater than 6:", len(unusual_balls))

display(unusual_balls.head(25))

Deliveries with suffix greater than 6: 45

,MatchDay,Innings,Batting Team,Bowling Team,Striker,Bowler,Ball Number,Actual Ball Number,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye
18,1,1,West Indies Cricket Team,India National Cricket team,Kamil Pooran,Arshdeep Singh,2.7,2.6,0,0,0,0,0,0,0
194,1,2,India National Cricket team,West Indies Cricket Team,Ishan Kishan,Akeal Hosein,12.7,12.6,4,4,0,0,0,0,0
223,2,1,India National Cricket team,West Indies Cricket Team,Sanju Samson,Akeal Hosein,2.7,2.6,1,1,0,0,0,0,0
266,2,1,India National Cricket team,West Indies Cricket Team,Ishan Kishan,Shamar Joseph,9.7,9.6,4,4,0,0,0,0,0
279,2,1,India National Cricket team,West Indies Cricket Team,Sanju Samson,Roston Chase,11.7,11.6,1,1,0,0,0,0,0
286,2,1,India National Cricket team,West Indies Cricket Team,Sanju Samson,Romario Shepherd,12.7,12.3,1,0,1,1,0,0,0
287,2,1,India National Cricket team,West Indies Cricket Team,Sanju Samson,Romario Shepherd,12.8,12.4,1,1,0,0,0,0,0
288,2,1,India National Cricket team,West Indies Cricket Team,Shivam Dube,Romario Shepherd,12.9,12.5,0,0,0,0,0,0,0
320,2,1,India National Cricket team,West Indies Cricket Team,Shreyas Iyer,Shamar Springer,17.7,17.6,4,4,0,0,0,0,0
375,2,2,West Indies Cricket Team,India National Cricket team,Shai Hope,Shivam Dube,6.7,6.6,1,1,0,0,0,0,0
406,2,2,West Indies Cricket Team,India National Cricket team,Sherfane Rutherford,Axar Patel,11.7,11.6,2,2,0,0,0,0,0
413,2,2,West Indies Cricket Team,India National Cricket team,Sherfane Rutherford,Naman Dhir,12.7,12.6,6,6,0,0,0,0,0
438,2,2,West Indies Cricket Team,India National Cricket team,Romario Shepherd,Kuldeep Yadav,16.7,16.6,4,4,0,0,0,0,0
478,3,1,India National Cricket team,West Indies Cricket Team,Abhishek Sharma,Shamar Springer,4.7,4.6,6,6,0,0,0,0,0
491,3,1,India National Cricket team,West Indies Cricket Team,Abhishek Sharma,Keemo Paul,6.7,6.6,1,1,0,0,0,0,0
498,3,1,India National Cricket team,West Indies Cricket Team,Ishan Kishan,Gudakesh Motie,7.7,7.6,1,1,0,0,0,0,0
511,3,1,India National Cricket team,West Indies Cricket Team,Naman Dhir,Shamar Springer,9.7,9.6,1,1,0,0,0,0,0
590,3,2,West Indies Cricket Team,India National Cricket team,Shimron Hetmyer,Mayank Yadav,2.7,2.6,1,1,0,0,0,0,0
603,3,2,West Indies Cricket Team,India National Cricket team,Kamil Pooran,Prince Yadav,4.7,4.6,1,1,0,0,0,0,0
616,3,2,West Indies Cricket Team,India National Cricket team,Shimron Hetmyer,Naman Dhir,6.7,6.6,0,0,0,0,0,0,0
641,3,2,West Indies Cricket Team,India National Cricket team,Kamil Pooran,Naman Dhir,10.7,10.6,0,0,0,0,0,0,0
648,3,2,West Indies Cricket Team,India National Cricket team,Quentin Sampson,Prince Yadav,11.7,11.6,1,1,0,0,0,0,0
661,3,2,West Indies Cricket Team,India National Cricket team,Quentin Sampson,Arshdeep Singh,13.7,13.5,1,0,1,1,0,0,0
662,3,2,West Indies Cricket Team,India National Cricket team,Quentin Sampson,Arshdeep Singh,13.8,13.6,1,1,0,0,0,0,0
717,4,1,West Indies Cricket Team,India National Cricket team,Jewel Andrew,Mayank Yadav,2.7,2.5,2,2,0,0,0,0,0

In [13]:
unusual_balls["Is_Wide"] = unusual_balls["Wide"].fillna(0) > 0
unusual_balls["Is_No_Ball"] = unusual_balls["No Ball"].fillna(0) > 0

display(
    unusual_balls.groupby(
        ["Is_Wide", "Is_No_Ball"],
        dropna=False
    ).size().reset_index(name="Delivery_Count")
)

   Is_Wide  Is_No_Ball  Delivery_Count
0    False       False              40
1     True       False               5

In [14]:
# Compare Ball Number with Actual Ball Number

number_check = clean_df.copy()

number_check["Ball_Number_Difference"] = (
    number_check["Ball Number"]
    - number_check["Actual Ball Number"]
).round(1)

number_check["Is_Wide"] = (
    number_check["Wide"].fillna(0) > 0
)

number_check["Is_No_Ball"] = (
    number_check["No Ball"].fillna(0) > 0
)

print("Difference counts:")
display(
    number_check["Ball_Number_Difference"]
    .value_counts()
    .sort_index()
    .rename_axis("Difference")
    .reset_index(name="Count")
)

print("Examples where the ball numbers differ:")
display(
    number_check.loc[
        number_check["Ball_Number_Difference"] != 0,
        [
            "MatchDay",
            "Innings",
            "Ball Number",
            "Actual Ball Number",
            "Wide",
            "No Ball",
            "Team Runs",
            "Runs Off The Bat",
            "Extra",
        ],
    ].head(30)
)

Difference counts:

   Difference  Count
0        -0.5      1
1         0.0    795
2         0.1    130
3         0.2     20
4         0.3     10
5         0.4      3

Examples where the ball numbers differ:

     MatchDay  Innings  Ball Number  Actual Ball Number  Wide  No Ball  Team Runs  Runs Off The Bat  Extra
13          1        1        2.200                 2.1     0        0          0                 0      0
14          1        1        2.300                 2.2     0        0          0                 0      0
15          1        1        2.400                 2.3     0        0          1                 1      0
16          1        1        2.500                 2.4     0        0          1                 1      0
17          1        1        2.600                 2.5     0        0          0                 0      0
18          1        1        2.700                 2.6     0        0          0                 0      0
191         1        2       12.400                12.3     0        1          2                 1      1
192         1        2       12.500                12.4     0        0          1                 1      0
193         1        2       12.600                12.5     0        0          1                 1      0
194         1        2       12.700                12.6     0        0          4                 4      0
219         2        1        2.300                 2.2     0        1          0                 0      1
220         2        1        2.400                 2.3     0        0          6                 6      0
221         2        1        2.500                 2.4     0        0          0                 0      0
222         2        1        2.600                 2.5     0        0          2                 2      0
223         2        1        2.700                 2.6     0        0          1                 1      0
265         2        1        9.600                 9.5     1        0          1                 0      1
266         2        1        9.700                 9.6     0        0          4                 4      0
276         2        1       11.400                11.3     1        0          1                 0      1
277         2        1       11.500                11.4     0        0          0                 0      0
278         2        1       11.600                11.5     0        0          1                 1      0
279         2        1       11.700                11.6     0        0          1                 1      0
281         2        1       12.200                12.1     1        0          1                 0      1
282         2        1       12.300                12.1     1        0          1                 0      1
283         2        1       12.400                12.1     0        0          4                 4      0
284         2        1       12.500                12.2     0        0          1                 1      0
285         2        1       12.600                12.3     0        0          1                 1      0
286         2        1       12.700                12.3     1        0          1                 0      1
287         2        1       12.800                12.4     0        0          1                 1      0
288         2        1       12.900                12.5     0        0          0                 0      0
289         2        1       12.101                12.6     0        0          1                 1      0

In [15]:
# Inspect a section of MatchDay 2, Innings 1

sequence_check = clean_df.loc[
    (clean_df["MatchDay"] == 2)
    & (clean_df["Innings"] == 1),
    [
        "Ball Number",
        "Actual Ball Number",
        "Striker",
        "Bowler",
        "Team Runs",
        "Wide",
        "No Ball",
        "Wicket",
    ],
].copy()

display(
    sequence_check.loc[
        (sequence_check["Ball Number"] >= 11.0)
        & (sequence_check["Ball Number"] <= 13.0)
    ]
)

     Ball Number  Actual Ball Number       Striker            Bowler  Team Runs  Wide  No Ball  Wicket
273       11.100                11.1  Ishan Kishan      Roston Chase          0     0        0       1
274       11.200                11.2   Shivam Dube      Roston Chase          0     0        0       0
275       11.300                11.3   Shivam Dube      Roston Chase          0     0        0       0
276       11.400                11.3   Shivam Dube      Roston Chase          1     1        0       0
277       11.500                11.4   Shivam Dube      Roston Chase          0     0        0       0
278       11.600                11.5   Shivam Dube      Roston Chase          1     0        0       0
279       11.700                11.6  Sanju Samson      Roston Chase          1     0        0       0
280       12.100                12.1  Sanju Samson  Romario Shepherd          1     1        0       0
281       12.200                12.1  Sanju Samson  Romario Shepherd          1     1        0       0
282       12.300                12.1  Sanju Samson  Romario Shepherd          1     1        0       0
283       12.400                12.1  Sanju Samson  Romario Shepherd          4     0        0       0
284       12.500                12.2  Sanju Samson  Romario Shepherd          1     0        0       0
285       12.600                12.3   Shivam Dube  Romario Shepherd          1     0        0       0
286       12.700                12.3  Sanju Samson  Romario Shepherd          1     1        0       0
287       12.800                12.4  Sanju Samson  Romario Shepherd          1     0        0       0
288       12.900                12.5   Shivam Dube  Romario Shepherd          0     0        0       0
289       12.101                12.6   Shivam Dube  Romario Shepherd          1     0        0       0

In [16]:
# Inspect the suspicious ball-number record

row = clean_df.loc[
    (clean_df["MatchDay"] == 2)
    & (clean_df["Innings"] == 1)
    & (clean_df["Ball Number"] > 12.9)
    & (clean_df["Ball Number"] < 12.2 + 1),
    ["Ball Number", "Actual Ball Number", "Wide", "No Ball"]
]

display(row.tail(10))

print("Ball Number dtype:", clean_df["Ball Number"].dtype)
print("Actual Ball Number dtype:", clean_df["Actual Ball Number"].dtype)

     Ball Number  Actual Ball Number  Wide  No Ball
290         13.1                13.1     0        0

Ball Number dtype: float64
Actual Ball Number dtype: float64

In [17]:
# Create a text version of Ball Number for display
clean_df["Ball_Number_Label"] = clean_df["Ball Number"].map(
    lambda x: f"{int(x)}.{int(round((x - int(x)) * 1000))}"
    if (x - int(x)) >= 0.1
    else f"{x:.1f}"
)

# Correct the specific row: MatchDay 2, Innings 1, delivery currently shown as 12.101
mask = (
    (clean_df["MatchDay"] == 2)
    & (clean_df["Innings"] == 1)
    & (clean_df["Ball Number"] > 12.9)
    & (clean_df["Ball Number"] < 12.11)
)

clean_df.loc[mask, "Ball_Number_Label"] = "12.10"

# Verify the correction
display(
    clean_df.loc[
        (clean_df["MatchDay"] == 2)
        & (clean_df["Innings"] == 1)
        & (clean_df["Ball Number"] > 12.9)
        & (clean_df["Ball Number"] < 12.11),
        ["Ball Number", "Ball_Number_Label", "Actual Ball Number"]
    ]
)

Empty DataFrame
Columns: [Ball Number, Ball_Number_Label, Actual Ball Number]
Index: []

In [18]:
# Find the suspicious row using its original row index
print("Original Ball Number:", clean_df.loc[289, "Ball Number"])
print("Actual Ball Number:", clean_df.loc[289, "Actual Ball Number"])

# Create the display-label column if it doesn't exist
if "Ball_Number_Label" not in clean_df.columns:
    clean_df["Ball_Number_Label"] = clean_df["Ball Number"].astype(str)

# Correct the display label for row 289
clean_df.loc[289, "Ball_Number_Label"] = "12.10"

# Verify
display(
    clean_df.loc[[289], [
        "MatchDay",
        "Innings",
        "Ball Number",
        "Ball_Number_Label",
        "Actual Ball Number"
    ]]
)

Original Ball Number: 12.101
Actual Ball Number: 12.6

     MatchDay  Innings  Ball Number Ball_Number_Label  Actual Ball Number
289         2        1       12.101             12.10                12.6

In [19]:
clean_df.to_csv(clean_path, index=False)
print("Saved successfully to:", clean_path)

Saved successfully to: C:\India_Vs_West_Indies_T20i_Challenge\Data\Clean\t20i_ball_by_ball_clean.csv

In [20]:
# Review the two unresolved scoring records
display(
    clean_df.loc[[219, 458], [
        "MatchDay",
        "Innings",
        "Batting Team",
        "Striker",
        "Bowler",
        "Ball Number",
        "Actual Ball Number",
        "Team Runs",
        "Runs Off The Bat",
        "Extra",
        "Wide",
        "No Ball",
        "Leg Bye",
        "Bye",
        "Run_QC_Flag",
        "Extras_QC_Flag"
    ]]
)

,MatchDay,Innings,Batting Team,Striker,Bowler,Ball Number,Actual Ball Number,Team Runs,Runs Off The Bat,Extra,Wide,No Ball,Leg Bye,Bye,Run_QC_Flag,Extras_QC_Flag
219,2,1,India National Cricket team,Sanju Samson,Akeal Hosein,2.3,2.2,0,0,1,0,1,0,0,True,False
458,3,1,India National Cricket team,Ishan Kishan,Shamar Joseph,1.5,1.5,4,0,1,0,0,0,4,True,True

In [21]:
# Correct row 219: no-ball extra was recorded, but team runs were typed incorrectly
clean_df.loc[219, "Team Runs"] = 1

# Correct row 458: four byes were recorded, but total extras were typed incorrectly
clean_df.loc[458, "Extra"] = 4

# Update quality-control flags
clean_df["Run_QC_Flag"] = (
    clean_df["Team Runs"]
    != clean_df["Runs Off The Bat"] + clean_df["Extra"]
)

clean_df["Extras_QC_Flag"] = (
    clean_df["Extra"]
    != clean_df[["Wide", "No Ball", "Leg Bye", "Bye"]].sum(axis=1)
)

# Verify remaining issues
print("Team-run inconsistencies:", clean_df["Run_QC_Flag"].sum())
print("Extras inconsistencies:", clean_df["Extras_QC_Flag"].sum())

Team-run inconsistencies: 0
Extras inconsistencies: 0

In [22]:
clean_df.to_csv(clean_path, index=False)
print("Corrected dataset saved:", clean_path)

Corrected dataset saved: C:\India_Vs_West_Indies_T20i_Challenge\Data\Clean\t20i_ball_by_ball_clean.csv

In [23]:
# Validate totals for every innings

innings_summary = (
    clean_df.groupby(
        ["MatchDay", "Innings", "Batting Team", "Bowling Team"],
        as_index=False
    )
    .agg(
        Deliveries=("Team Runs", "size"),
        Team_Runs=("Team Runs", "sum"),
        Batter_Runs=("Runs Off The Bat", "sum"),
        Extras=("Extra", "sum"),
        Wickets=("Wicket", "sum"),
        Fours=("4's", "sum"),
        Sixes=("6's", "sum")
    )
)

innings_summary["Runs_Reconciled"] = (
    innings_summary["Team_Runs"]
    == innings_summary["Batter_Runs"] + innings_summary["Extras"]
)

display(innings_summary)

print(
    "Innings with inconsistent totals:",
    (~innings_summary["Runs_Reconciled"]).sum()
)

   MatchDay  Innings                 Batting Team                 Bowling Team  Deliveries  Team_Runs  Batter_Runs  Extras  Wickets  Fours  Sixes  Runs_Reconciled
0         1        1     West Indies Cricket Team  India National Cricket team         116        171          163       8       10     17      8             True
1         1        2  India National Cricket team     West Indies Cricket Team          89        172          171       1        2     19      7             True
2         2        1  India National Cricket team     West Indies Cricket Team         128        249          240       9        5     25     13             True
3         2        2     West Indies Cricket Team  India National Cricket team         115        252          248       4        4     21     20             True
4         3        1  India National Cricket team     West Indies Cricket Team         124        223          213      10       10     24      8             True
5         3        2     West Indies Cricket Team  India National Cricket team         127        209          199      10        7     15     13             True
6         4        1     West Indies Cricket Team  India National Cricket team         130        247          229      18        3     16     16             True
7         4        2  India National Cricket team     West Indies Cricket Team         130        223          199      24        9     15     13             True

Innings with inconsistent totals: 0